drop table user if exists;
create table user (
  id int generated by default as identity,
  createTime varchar(20) ,
  name varchar(20),
  password varchar(36),
  phone varchar(20),
  nickName varchar(20),
  gender varchar(20),
  primary key (id)
);

drop table "order" if exists;
create table "order" (
  id int generated by default as identity,
  createTime varchar(20) ,
  userId int,
  amount int,
  orderNo varchar(32),
  address varchar(20),
  primary key (id)
);

