drop table user if exists;
create table user (
  id int generated by default as identity,
  createTime varchar(20) ,
  name varchar(20),
  password varchar(36),
  phone varchar(20),
  nickName varchar(20),
  gender varchar(20),
  primary key (id)
);


